# Generated by Django 5.1.7 on 2025-03-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TOdoModer',
            new_name='TOdoModel',
        ),
    ]
